services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

    docker run -it \
      -e POSTGRES_USER="pc" \
      -e POSTGRES_PASSWORD="root" \
      -e POSTGRES_DB="ny_taxi" \
      -v c:/Users/pc/Documents/projects/data_engineering/week_1_basics_n_setup/docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data \
      -p 5432:5432 \
     postgres:13

     -- volumnes is for mapping a folder on the host machine to a folder in the container
     --  -p: we also need to map a port on our host machine to a port in the container. This is 
     -- needed to send request(sql queries) to the database.

     docker run -it \
       -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
       -e PGADMIN_DEFAULT_PASSWORD="root" \
       -p 8080:80 \
      dpage/pgadmin4

      -- ON DOCKER NETWORK
    docker run -it \
      -e POSTGRES_USER="root" \
      -e POSTGRES_PASSWORD="root" \
      -e POSTGRES_DB="ny_taxi" \
      -v c:/Users/pc/Documents/projects/data_engineering/week_1_basics_n_setup/docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data \
      -p 5432:5432 \
      --network pg-network \
      --name pgdatabase \
     postgres:13 

     docker run -it \
      -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
      -e PGADMIN_DEFAULT_PASSWORD="root" \
      -p 8080:80 \
      --network pg-network \
      --name pgadmin \
     dpage/pgadmin4

    URL="http://192.168.0.199:8000/yellow_tripdata_2021-01.csv"

    python ingest_data.py \
      --user=root \
      --password=root \
      --host=localhost \
      --port=5432 \
      --db=ny_taxi \
      --table_name=yellow_taxi_data \
      --url=${URL}

 
 docker build -t taxi_ingest:v001 .


      docker run -it \
       --network pg-network \
       taxi_ingest:v001 \
         --user=root \
        --password=root \
        --host=pgdatabase \
        --port=5432 \
        --db=ny_taxi \
        --table_name=yellow_taxi_data \
        --url=${URL}